{% set name = "repeated_test" %}
{% set version = "2.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/repeated_test-{{ version }}.tar.gz
  sha256: 4db572400ec48c24b0a3aa9f0e4b1b13c214d44964482001114056cb98f52897

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - six >=1.7

test:
  imports:
    - repeated_test
    - repeated_test.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/epsy/repeated_test
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A quick unittest-compatible framework for repeating a test function over many fixtures
  dev_url: https://github.com/epsy/repeated_test

extra:
  recipe-maintainers:
    - proinsias
