appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: SZvyHo/e7J44E5WYZFSajiqCGkVFf3TBS9ThsHnIX7QxpaFefh+cJlXLw9IyTjx2DEBg/E+l+7znwsfLz3mmxsf2YTITBtxtgfruxuYlV9CRco+LrPFcfEZMg/UIJlKW/LZy6kWnf1oZbLHNt2cMsUsXgPKiFFTr5OOl2DRECqDbRoIuOE1KfKnjLo1O5Y0salJXvaZkhQWlB2ea3Iza5G5iyNN8+IQAhldl4dYF3VjQpgV3wf89HRl9Y3gi/Pd7eAkDcenYHiixHCO7K7mjQu9i93rP8z3fAHbUYTaIo13rITBoLxjFSQjavdtuC8QbhoRnulixtTK7c+PFyzq2eDyqShcphWWdGLOhUzO2fEfyNLZDBeh3wFFYoLhHWrPrmX3TTtJW1ueN4cJA/rnwiZTvxGPwas9LQAxJc21yxDC7I1laFC3IGEkNUMjiul26ZJttSiaO1bYPhPznwaYBoNJeHYxswTgV3dMmXbNmW0wLkMSn7cjJXAX6Jfwdft+74y2tFybc3Ayi3tSNqa2NEzTt6JWLeF+L+bNdiSTJfbwYLI8cmh7jj5KsR+8dvbNuh2CwRO/JW7wNxbGsg3z2RMMI08jObVvTT5Am+Jv98aR3Qn91a0lbrWrnUlqQgsbT0Gj9W7YSaIbcQKS14hcOearwzfb1q4xi4+xoocw35jQ=}
conda_forge_output_validation: true
bot:
  automerge: true
